### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by skinatro** [mishraaditya595/Scanner#76]
**Releasing F-Droid builds**

A brief description of the question or issue:

F-Droid is a FOSS only store for android, so it would be pretty convenient to have the app on F-Droid as well as well as a GPlayStore build. (considering the app is open source as well)

For more information check this out [https://f-droid.org/](https://f-droid.org/)

**Comment by icebarf** [comment]
hi, are you asking that fdroid be released on: Fdroid "and Google Play Store" ?

**Comment by skinatro** [comment]
> hi, are you asking that fdroid be released on: Fdroid "and Google Play Store" ?

No I am talking about the app to be released on f-droid

**Comment by icebarf** [comment]
Hain
```
                 ________
Your issue -> --|my head | --->
```
